version: '3.9'
services:
    denver:
        container_name: denver
        image: denverhelper:latest
        restart: always
        build:
            context: ./
            dockerfile: ./Dockerfile